config/routes.rb
Rails.application.routes.draw do

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :microposts

  resources :users
  resources :projects do
    resources :tasks, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]

  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

  root 'projects#index'
  

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
	
	validates :title, 
	presence: { message: "入力してください" },
	length: { minimum:2, maximum:10, message: "２文字以上１０文字以内で入力してください" }
	#length: { minimum:3, message: "２文字以上で入力してください" },
	#length: { maximum:10, message: "１０文字以内で入力してください" }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
 	before_action :set_project, only: [:show, :edit, :update, :destroy]
	#after_action 
    def index
        @projects = Project.all
    end

    def show
        #@project = Project.find(params[:id])
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)
        if @project.save
        	redirect_to projects_path
        else
        	render "new"
        end
    end

    def edit
       #@project = Project.find(params[:id])
    end

    def update
       #@project = Project.find(params[:id])
        if @project.update(project_params)
        	redirect_to projects_path
        else
        	render "edit"
        end
    end

    def destroy
       #@project = Project.find(params[:id])
       @project.destroy
       redirect_to projects_path
    end

    private
	    def project_params
	        params[:project].permit(:title)
	    end

	    def set_project
	       @project = Project.find(params[:id])
	    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

<p>
	<% if @project.errors.any? %>
	<%= @project.errors.messages[:title][0] %>	
	<% end %>
	<%= f.label :title %></br>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<% provide(:title, 'Projects') %>
<h1>Projects</h1>
<u1>
  <% @projects.each do |project| %>
  <li>
    <%= link_to project.title, project_path(project.id)%>
    (<%= project.tasks.unfinished.count%> / <%= project.tasks.count%>)
    <%= link_to "[edit]", edit_project_path(project.id)%>
    <%= link_to "[delete]", project_path(project.id), method: :delete,data: { confirm: "削除してよろしいですか？" }%>
  </li>
  <% end %>
</u1>
<p><%= link_to "Add New", new_project_path%>

app/views/projects/new.html.erb
<h1>Add New</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<u1>
  <li>projectId:<%= @project.id%></li>
  <% @project.tasks.each do |task| %>
  <li>
    <%= check_box_tag '', '', task.done, {"data-id" => task.id, "data-project_id" => task.project_id} %>    
    taskTitle:<%= task.title %>
    <%= link_to "[delete]", project_task_path(task.project.id, task.id), method: :delete,data: { confirm: "削除してよろしいですか？" }%>

  </li>
  <% end %>
  <li>
    <%= form_for [@project, @project.tasks.build] do |f| %>
    <%= f.text_field :title %>
    <%= f.submit %>
	<% end %>
  </li>
</u1>

<script>
$(function(){
  $("input[type=checkbox]").click(function(){
    $.post('/project/'+$(this).data('project_id')+'/tasks/'+$(this).data('id')+'/toggle');
  });
});
</script>