config/routes.rb
Rails.application.routes.draw do

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :microposts

  resources :users
  resources :projects do
    resources :tasks, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]

  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

  root 'projects#index'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.jp/">Rails Tutorial</a>
    by XXXXX
  </small>
  <nav>
    <ul>
      <li><%= link_to "home", "/" %></li>
      <li><%= link_to "projects", projects_path %></li>
      <li><%= link_to "users", users_path %></li>
      <li><%= link_to "Sign up", signup_path %></li>
      <li><%= link_to "microposts", microposts_path %></li>
      <li><%= link_to "StaticPages_Home", home_path %></li>
      <li><%= link_to "StaticPages_Help", help_path %></li>
      <li><%= link_to "StaticPages_about", about_path %></li>
      <li><%= link_to "StaticPages_contact", contact_path %></li>
      <li><%= link_to "signin", signin_path %></li>
      <li><a href="http://news.railstutorial.jp/">railstutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Demo app", root_path, id: "logo", class: "navbar-brand" %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "ホーム", root_path %></li>
          <li><%= link_to "ヘルプ", help_path %></li>
          <!-- ログイン状態によってメニューを変化 -->
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">アカウント<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <!-- <li><%= link_to "ユーザの編集", "#", :class => 'navbar-link' %></li> -->
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: :delete, :class => 'navbar-link'%></li>
                </ul>
              </ul>
            </li>
          <% else %>
            <li><%= button_to "ログイン", signin_path, :class => "btn btn-primary navbar-btn" %></li>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </div> <!-- /. navbar-collapse -->
    </div> <!-- /. container -->
  </div> <!-- /. navbar-inner -->
</header>

app/views/layouts/_header.html_old.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Demo app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    '#' %></li>
          <li><%= link_to "Help",    '#' %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%#<title>demoApp <%= yield(:title) %><%#</title>%>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div class="container">
	  <%= render 'layouts/header' %>
    <p class="center"><%= image_tag "header.jpg", :alt => 'header' %></p>
    <% flash.each do |key, value| %>
      <% status = key == :notice ? "success" : "danger" %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>